#  /$$      /$$ /$$                      /$$$$$$                  /$$
# | $$$    /$$$|__/                     /$$__  $$                | $$
# | $$$$  /$$$$ /$$ /$$$$$$$   /$$$$$$ | $$  \__/  /$$$$$$   /$$$$$$$  /$$$$$$
# | $$ $$/$$ $$| $$| $$__  $$ /$$__  $$| $$       /$$__  $$ /$$__  $$ /$$__  $$
# | $$  $$$| $$| $$| $$  \ $$| $$$$$$$$| $$      | $$  \ $$| $$  | $$| $$$$$$$$
# | $$\  $ | $$| $$| $$  | $$| $$_____/| $$    $$| $$  | $$| $$  | $$| $$_____/
# | $$ \/  | $$| $$| $$  | $$|  $$$$$$$|  $$$$$$/|  $$$$$$/|  $$$$$$$|  $$$$$$$
# |__/     |__/|__/|__/  |__/ \_______/ \______/  \______/  \_______/ \_______/

startCoins: 0
vault: false
# miliseconds until the player's coins get updated (only avaiable if vault and SQL = true)
refreshDelay: 10000
